source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'phoneid_iOS_Example_swift' do
  platform :ios, '9.0'
  pod "phoneid_iOS", :path => "../"
end

target 'phoneid_iOS_Example_objc' do
  platform :ios, '9.0'
  pod "phoneid_iOS", :path => "../"
end

target 'phoneid_iOS_Tests' do
  platform :ios, '9.0'
  pod "phoneid_iOS", :path => "../"
end
